on: [push, pull_request]

name: test
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: Install code check tools
        run: |
          pip install pre-commit
          go install golang.org/x/tools/cmd/goimports@latest
          go install golang.org/x/lint/golint@latest
          go install github.com/fzipp/gocyclo/cmd/gocyclo@latest

      - name: Code checks
        run: pre-commit run --all-files

  test:
    strategy:
      matrix:
        go-version:
          - 1.13.x
          - 1.14.x
          - 1.15.x
          - 1.16.x
          - 1.17.x
          - 1.18.x
          - 1.19.x
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: go build -race ./...

      - name: Test
        run: >
          go test
          -race
          -coverpkg=all
          -coverprofile=coverage.txt
          -covermode=atomic
          ./...

      - uses: codecov/codecov-action@v1
        if: ${{ matrix.go-version == '1.19.x' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}>
